### ISSUE TITLE
Have the core sass files available as a component

### ISSUE THREAD

**Issue by GreenDude** [ericam/susy#147]
While the plugin is nice as-is (kudos), I would really like to use a tool like [bower](https://github.com/twitter/bower) to manage the core of susy as a package.

It would suffice to add the `sass` folder to a separate repo and include it within the main repo as a submodule or otherwise. [I've set up a repo](https://github.com/GreenDude/susy-core) with a simple `component.json` to test it with bower and I think it's pretty sweet.

Besides the compass project template are there anymore downsides to not using the full plugin? I've almost never used templates in general so that's fine with me. There's also the perk of having 1 less gem dependency and not editing the `config.rb` 

Of course, you would `@import "susy-core/susy"` instead of just `@import "susy"` for this setup:

```
/project
    /components-land-here/
        /susy-core
        ...
    style.scss
```
With `components-land-here` set as my `sass_dir`.

A workaround would be to hold [the susy subfolder](https://github.com/ericam/susy/tree/master/sass/susy) in the second repo instead so that component users will have less redundant imports while the shorthand partial stays in the plugin repo. 

```scss
@import "susy-core/support";
@import "susy-core/units";

@import "susy-core/settings";
@import "susy-core/functions";
@import "susy-core/grid";
@import "susy-core/padding";
@import "susy-core/margin";
@import "susy-core/media";
@import "susy-core/background";
```

Importing each partial on its own line is a reasonable trade imo and it's also more aligned with the philosophy of small reusable components.

For example, I would like to use `units` for its rem mixins on a project that doesn't necessarily need a susy grid.

What do you think?

**Comment by ericam** [comment]
I think this has been covered by the LibSass bower/npm/eyeglass packages.
