### ISSUE TITLE
Ability to debug grid, semantically

### ISSUE THREAD

**Issue by briangonzalez** [ericam/susy#293]
I've used Susy throughout many projects now, and I love the declarative style where I can apply my grid directly in Sass.

One of my biggest pain points, as opposed to other grids systems which require one to author their grid using CSS classes, is that I cannot see the how the grid was applied to a given element when I am debugging in dev tools.

My idea is simple:

* Allows devs to put Susy into verbose debug mode, `$verbose-debug-mode: true;` 
* When in verbose debug mode, Susy would output grid information about the element onto unused CSS properties:

```css
@mixin span-columns($col, $cols) {
  /* current Susy code.... */
  susy-grid: $col of $cols;
}
```

If the powers to be like this feature, I'd be more than happy to implement it.

__Example:__

```css
.box{ @include span-columns(6,12); }
```

![screen shot 2014-01-28 at 11 33 20 am](https://f.cloud.github.com/assets/659829/2023039/8d3fcd2a-8855-11e3-8474-de8d802eb623.png)

**Comment by ericam** [comment]
This was completed and released some time ago! Yay!
