### ISSUE TITLE
Exploring split gutter-position

### ISSUE THREAD

**Issue by DavidOliver** [ericam/susy#324]
Susy 2.1.1.

I've got the basis of a responsive grid up and running using `after` for `gutter-position`, but was hoping to look into using `split` instead to avoid having to use `last` or `omega` on any columns at the end of the container.

However, I'm using Foundation 5 which applies `border-box` to everything, and although I've set `global-box-sizing` in `$susy` to `border-box` it doesn't seem to be applied when `gutter-position` is `split`. With a `gutter-position` of `after` it doesn't seem to be a problem.

**Comment by ericam** [comment]
Digging into this again, the margin-left seems to come from `pre` (so no bug with `nest` as far as I can tell). The bug with `pre` should be fixed by 448d21321d5
