### ISSUE TITLE
Optimising Compile time

### ISSUE THREAD

**Issue by Timoti** [ericam/susy#325]
I've had a lot of issues with compile times on susyone - using this for Drupal Omega 4 theming.  

With the help of a cool ruby guru - operating outside of his core competencies - we got compile down from 1m to 20-30s by making various imports much more specific - much better but still unacceptable And yes - my code is an @extend free zone.

from GemFile:
```
 # Sass, Compass and extensions.
  gem 'sass'      # Sass.
  gem 'sass-globbing'           # Import Sass files based on globbing pattern.
  gem 'compass', '= 1.0.0.alpha.19'                  # Framework built on Sass.
  gem 'compass-validator'       # So you can `compass validate`.
  gem 'compass-normalize'       # Compass version of normalize.css.
  gem 'compass-rgbapng'         # Turns rgba() into .png's for backwards compatibility.
  gem 'susy', ">=2.0"           # Susy grid framework.
  # gem 'singularitygs'         # Alternative to the Susy grid framework.
  gem 'toolkit', '~>2.0'                 # Compass utility from the fabulous Snugug.
  gem 'oily_png'                # Faster Compass sprite generation.
  gem 'css_parser'              # Helps `compass stats` output statistics.
```

Ideally I'd just be using libSASS for uberfast compiles, via codekit 2.0, but this isn't at all straightforward either, and there's no surety that sourcemaps are supported yet, operating in codekits 'hybrid' libsass/ruby approach. 

There is a lot of info out there on optimising for better css, but not actually for the compile time. So if anyone has any general guidelines for optimizing compiling - it would be great to hear 'em.

**Comment by DenisMir** [comment]
Any improvements on this issue? We also recognized the compile time issues especially with the `span` mixin which gets used pretty often. This single mixin eats up all the compile time improvements of the switch to libsass. (more about this can be found here: #465) At the moment our `@include span` calls make up 90% of the whole sass compile time.

**Comment by SachaMPS** [comment]
@DenisMir - latest susy is libsass friendly:
http://www.zell-weekeat.com/gulp-libsass-with-susy/

**Comment by DenisMir** [comment]
@SachaMPS 
Well I got the same problems when skipping grunt and using node-sass directly.

**Comment by SachaMPS** [comment]
@DenisMir: Sorry, i didnt read your previous message correct.

**Comment by DenisMir** [comment]
@SachaMPS Ok fine. :-) I'm just wondering why this is no problem for other users of susy. Each `@include span` call adds 20ms to the compilation time with libsass. (50ms would be the compilation time in total without the `span` calls)

**Comment by rryter** [comment]
I'm experiencing this problem too. What is the current situation here?

**Comment by HugoGiraudel** [comment]
Is this issue still relevant?

**Comment by SachaMPS** [comment]
In my opinion no more since susy works perfectly with libsass

**Comment by ericam** [comment]
We won't be making major changes to this in Susy 2. We should do what we can to follow best performance practice for v3.

**Comment by kaij** [comment]
Very surprised that this got closed so quickly. Susy definitely has a performance problem, even when using libsass (it just takes more spans...). Applying several performance optimization (see idlfloods comments) helps - but so far they are not integrated in the master branch. I wonder why...

**Comment by ericam** [comment]
We are addressing this - just not as a bug fix. The major issues are so engrained in v2 that any suitable fix would require changes to the API (removing nested maps, etc) or massive restructuring. So far none of those optimizations are actually ready for merge, but v3 is coming along nicely in the `three` branch. There, we can address all the performance issues from the ground up in slimmer, with more modular code.

**Comment by kaij** [comment]
Thanks for the explanation! Good to know about the three branch...

**Comment by talbs** [comment]
Just found this thread, super helpful for some local compile times we've been seeing. Love Susy and now we're looking forward to v3 even more. :)

**Comment by ericam** [comment]
I just ran a rough benchmark test comparing v2 `span()` function with v3 `susy-span()` function. Don't worry, that name-spacing will be removable. Here's the test:

```scss
// Susy Two
@for $i from 1 through 500 {
  $span: span(3em);
  $span: span(3);
  $span: span(3 at 2);
  $span: span(6 'wide');
  $span: span(2 'static' ('column-width': 5em));
}

// Susy Three
@for $i from 1 through 500 {
  $span: susy-span(3em);
  $span: susy-span(3);
  $span: susy-span(3 at 2);
  $span: susy-span(6 'wide');
  $span: susy-span(2, $math: 'static', $column-width: 5em);
}
```

That's 2500 function calls each — much larger (I hope) than your average project. I ran the tests three times (to account for variation) in Ruby Sass (for worst case) with the following results:

*Susy Two*
1. 41.192s
2. 37.719s
3. 41.070s

*Susy Three*
1. 8.529s
2. 8.293s
3. 7.972s

Unless I'm missing something, I think we're on the right track. We have eliminated several known performance issues:

- no more nested maps anywhere
- validation is never duplicated (this shaved a second or two off the time in v3)
- the parser doesn't use nested loops for comparing keywords
- there is less shorthand syntax to parse (only tested in the final function)

It might be fun to compare some other bits (like the parser, settings-access, or Su updates) to see where we're saving most of that time.

**Comment by HugoGiraudel** [comment]
\o/

**Comment by ericam** [comment]
And that's not to say we're done tracking down The Slow Things :)

**Comment by davimachado** [comment]
Oh my  :O

**Comment by xzyfer** [comment]
This is awesome! LibSass is also getting a speed boost in 3.3 so this will fly!

**Comment by jasonsemko** [comment]
@ericam noticed that development on three stopped few weeks ago (no commits pushed), wanted to checkin on the status and see if it's still in the works. Really excited about the performance gains! Thanks

**Comment by ericam** [comment]
@jasonsemko The core is all done, and then work picked up heavily for me. In my dream world, everyone uses those core functions to build their own mixin system. I'm not sure if that's realistic - so the next step would be building a few simple systems for people to choose from. Any interest in helping make that happen?
