### ISSUE TITLE
Compass installation does not work

### ISSUE THREAD

**Issue by acjay** [ericam/susy#350]
I tried to install the latest Susy through the latest Compass, using the command from the docs `compass create --using susy <project name>`, but I got the error `No such framework: "susy"`. Prior to running that command, I had installed each through `gem`. Am I doing this wrong, or does this method no longer work?

My goal is to package up Susy as a [Webjar](http://www.webjars.org/contributing), so it can easily be used with the Play framework.

**Comment by HugoGiraudel** [comment]
Is this issue still relevant?
