### ISSUE TITLE
@include gallery(12 of 12) shouldn't stack on each other

### ISSUE THREAD

**Issue by anthonyholmes** [ericam/susy#352]
The gallery mixin is great. However, if you need to display only one per row at a small size, `@include gallery(12 of 12)` stacks all the elements in one row and on top of each other.

I've been adding `float: none;` but would like to see that automatically added at full-span.

**Comment by hal-gh** [comment]
+1

**Comment by cargoodrich** [comment]
Also having this issue. Has a solution been found yet? (aside from having to add clear: both !important; underneath where @include gallery(12 of 12); is specified?)

**Comment by Zwieks** [comment]
Had the same issue.. and what helped for me was adding:
```
@include gallery(12 of 12);
float:none;
margin-right:0;
```

**Comment by ericam** [comment]
I'm curious why you would use `gallery(12 of 12)` at all. The gallery mixin isn't doing anything useful there. You actually just want to override what the `gallery` mixin *was doing* before. I'd recommend putting the media-query wrapper around the other gallery mixin, so you don't have to override anything at all:

```scss
.block{
  // Block elements default to full width.

  @media (min-width: 60em) {
    @include gallery(4 of 12);
  }
}
```

**Comment by anthonyholmes** [comment]
I agree. Your mobile-first approach is perfect. Back on Jun 13, 2014, designing for Desktop first and max-width media queries is where the issue would come in.
