### ISSUE TITLE
How to hide debug handle?

### ISSUE THREAD

**Issue by johannesjo** [ericam/susy#358]
There must be a way, but I can't find an answer anywhere.

**Comment by maxfell** [comment]
I have been able to reproduce the error. Susy shows the toggle on every site even though it is disabled.

Here is the scss code:
```scss
.grid-example-container {
  @include container;
}
```

This is the Susy configuration:
```scss
$susy: (
  flow: ltr,
  math: fluid,
  output: float,
  gutter-position: split,
  container: auto,
  container-position: center,
  columns: 12,
  gutters: 0.25,
  column-width: false,
  global-box-sizing: border-box,
  last-flow: to,
  debug: (
    image: hide,
    color: rgba(#66f, 0.25),
    output: overlay,
    toggle: top right,
  ),
  use-custom: (
    background-image: false,
    background-options: false,
    box-sizing: true,
    clearfix: false,
    rem: true,
  )
);
```

http://sassmeister.com/gist/eb99db5e759d5683c1ad (click on "HTML" in the upper right corner and then type something random in the scss-pane to make it reload)

**Comment by ericam** [comment]
Interesting. The `output: overlay` setting seems to display it no matter what the debug `image` is set to. Thanks for tracking this down!

**Comment by maxfell** [comment]
Hey @ericam! Thanks for looking into it. Have you had a chance to investigate any further already?

**Comment by HugoGiraudel** [comment]
What about changing [this](https://github.com/ericam/susy/blob/master/sass/susy/language/susy/_background.scss#L18) to:

```scss
@if $_output == 'overlay' and susy-get('debug' 'image', $grid) != 'hide' {
```

**Comment by ericam** [comment]
@HugoGiraudel sounds good - go for it.

**Comment by HugoGiraudel** [comment]
Done in https://github.com/ericam/susy/commit/f26becea7f2406112445dd55535b879a1b4bd5cc.

**Comment by maxfell** [comment]
@HugoGiraudel Thank you!
