### ISSUE TITLE
Add Clarification About Use Of Inside-Static Gutter Position To Docs

### ISSUE THREAD

**Issue by Undistraction** [ericam/susy#368]
Having just set up a simple layout with fluid columns and fixed gutters, I found this surprisingly confusing.

Given that this is a very popular layout, the solution is very counter-intuitive. From the docs I would assume this would work:

```
$default-layout: (
  global-box-sizing: border-box,
  columns: 12,
  container: rem-calc(1000),
  gutter-position: inside-static,
  gutters: rem-calc(20)
);

```

However the only solution I've found is:

```
$gutter-width: rem-calc(10);
$pointless-column-width: rem-calc(1);

// Default layout
$default-layout: (
  global-box-sizing: border-box,
  columns: 12,
  container: rem-calc(1000),
  gutter-position: inside-static,
  column-width: $pointless-column-width,
  gutters: $gutter-width/$pointless-column-width
);
```
It seems that the value passed to `column-width` can be any non-zero value  and the result will be the same, which is obviously strange, but more confusingly, gutters are set as a ratio when it would seem obvious that as they are static, they should be passed as a specific value, and a column width has to be set, even though the column widths are percentages in a fluid layout.

**Comment by suprahfly** [comment]
So as I understand there is no clear way to set fluid grid with fixed width gutters?

**Comment by ericam** [comment]
You can do all that, just set a container width as well:

```
@include layout(100% fluid 12 20px inside-static);
```

I realize this isn't all obvious unless you understand the interplay between all those variables. I'd be happy for help improving the documentation.

**Comment by suprahfly** [comment]
Actually, I've find another way, just set containers to 100%. But your setup looks more elegant and I will definitely try it. In fact I've been experimenting with Susy just to see what I can reach. It is pretty awesome, man) But to be fair, in my humble opinion you give people too many ways to set one thing. This is convinient when you aware of logic, but confusing when you new to this. Maybe if we all go and try to level up the docs it become a whole different story. Sorry for my crappy english)

**Comment by albertopriore** [comment]
@ericam I'm trying something like this:

```
@include with-layout(100% fluid 12 20px inside-static) {
    @for $i from 1 to susy-get(columns)+1 {
      .box-#{$i} {
        @include span($i);
      }

      .box-#{$i}:last-child {
        margin-right: 0;
      }

      @for $n from 1 to $i {
        .box-#{$n}-of-#{$i} {
          @include span($n of $i);
        }

        .box-#{$n}-of-#{$i}:last-child {
          margin-right: 0;
        }
      }
    }
  }
```

But it throws a Sass::SyntaxError

```
Function valid-column-math finished without @return
```

What am I doing wrong?

**Comment by ericam** [comment]
Sorry, the `20px` is not a valid gutter setting. Gutters are always a ratio to columns (even when the colunms are actually fluid. So if you want `20px` gutters, you have to set `100% fluid 12 (100px 20px) inside-static` (where, in this case unfortunately, `100px` can be anything. :stuck_out_tongue: We're working on a better approach for v3.

**Comment by Dobby89** [comment]
I just came across this issue after struggling to set up a fixed gutter, but **fluid** grid myself. I don't feel the explanations above cut it for me, so I'm going to offer my own in case it helps anyone else in my position.

It seems that the following settings will deliver a fixed inside gutter of 10px (using padding).

```
$susy: (
  column-width: 100px,
  gutter-position: inside-static,
  gutters: 2 / 10
);
.grid-col {
  @include span(3 of 6);
}
```
Outputs:
```
.grid-col {
  box-sizing: border-box;
  width: 50%;
  float: left;
  padding-left: 10px;
  padding-right: 10px;
}
```

My understanding is `gutters: 2 / 10` = two 10ths of the `column-width: 100px`. which is **20px**.
This is then divided by 2 by Susy to get the fixed padding of **10px** on either side.

---

So to achieve a 15px gutter, you would use the following settings:

```
$susy: (
  column-width: 100px,
  gutter-position: inside-static,
  gutters: 3 / 10
);
.grid-col {
  @include span(3 of 6);
}
```
Outputs:
```
.grid-col {
  box-sizing: border-box;
  width: 50%;
  float: left;
  padding-left: 15px;
  padding-right: 15px;
}
```

Because `gutters: 3 / 10` = three 10ths of the `column-width: 100px`. which is **20px**
This is then divided by 2 by Susy to get the fixed padding of **15px** on either side.
