### ISSUE TITLE
Context with susy-breakpoint is creating incorrect outputs with asymmetric grids.

### ISSUE THREAD

**Issue by zellwk** [ericam/susy#373]
susy-breakpoints are creating different outputs when I try to use a nested context with asymmetric grids. Here are two variations I've tried: 

    // Variation 1: susy-breakpoint
    @include susy-breakpoint(700px, 3 of map-get($large, columns) at 2) {
      .text, h2 + .text {
        @include span(2 last);
      }
    }

    // Variation 2: breakpoint + nested
    @include breakpoint(700px) {
      @include nested(3 of map-get($large, columns) at 2) {
        &, h2 + & {
          @include span(2 last);
        }
      }
    }

The output for these two are different, even though they should be the same? 

    // Output from variation 1
    @media (min-width: 700px) {
      .text, h2 + .text {
        width: 57.14286%;
        float: left;
        margin-left: 42.85714%;
        margin-right: -100%;
      }
    }

![screen shot 2014-08-05 at 10 28 14 pm](https://cloud.githubusercontent.com/assets/3607637/3812692/c51b4e90-1cac-11e4-9ff1-841cf9f986b8.png)

    // Output from variation 2
    @media (min-width: 700px) {
      .text, h2 + .text {
        width: 76.31579%;
        float: left;
        margin-left: 23.68421%;
        margin-right: -100%;
      }
    }

![screen shot 2014-08-05 at 10 29 22 pm](https://cloud.githubusercontent.com/assets/3607637/3812714/f014cfe0-1cac-11e4-91b7-236ccb2a2429.png)

By looking at the grid and confirming it visually, `breakpoint` + `nested` is the correct output to go. Just wondering why `susy-breakpoint` doesn't seem to work. 

Here's `$susy` and `$large` that was mentioned in the above code: 

    $susy: (
      output: isolate,
      global-box-sizing: border-box,
      );

    $large: (
      columns: 1 2 3 4 5,
      gutter: 32 / 103
      );

Let me know if you need any more info for debugging!

**Comment by ericam** [comment]
Tracked it down to your code. :)

The problem is that `susy-breakpoint` doesn't accept a span (`3 of ... at 2`), only a layout (`map-get($large, columns)`). The correct comparison to `susy-breakpoint` is not `breakpoint` with `nested`, but `breakpoint` with `with-layout`.

It would be slick to allow both styles, but that's not how it works right now. I'd be happy to accept a patch, if you want to make one - but I don't plan to make feature changes to v2 myself. There is a `nested()` function you can use to get the layout:

```scss
$new-layout: nested(3 of map-get($large, columns) at 2);
@include susy-breakpoint(700px, $new-layout) {
  .text, h2 + .text {
    @include span(2 last);
  }
}
```
