### ISSUE TITLE
Analytics tools

### ISSUE THREAD

**Issue by ericam** [ericam/susy#384]
Was talking with @aaronagray about the potential for Susy to track your usage, and report back. This would be limited to things we can actually track — nothing related to the actual DOM. A few things we could potentially track:

- How many times you call various Susy mixins
- How often you repeat certain requests (e.g. calling `span(3 of 12)` 16 times)
- How often Susy gives the same output (even based on different requests)
- Something related to similar selector chains? (We can access this with `&` now in Sass-script)

Would that be useful? What other ideas do you have? What would you want to see in a report? Discuss!

**Comment by HugoGiraudel** [comment]
This should be done as a plugin and not part of the core I think. Also I am worried about the potential overhead it might introduce, especially in regard to performance.

> Compile time would be super useful and tracking that over releases. Is it going up or down?

You will be facing the Observer Paradox here. To track compile time, you are loading extra code which are resulting in longer compile time. :)

**Comment by ericam** [comment]
Yeah, I think the data is interesting - but in the end it would be easier to collect manually with a survey.
