### ISSUE TITLE
Support libsass

### ISSUE THREAD

**Issue by fpauser** [ericam/susy#390]
This would be great for all non-ruby susy users...

**Comment by tundrax** [comment]
libsass 3.1 has been released, any update on this issue?

**Comment by stevetweeddale** [comment]
Judging by https://github.com/ericam/susy/pull/406, this looks like this might even just need releasing!

This will be ace for our team - really excited about removing the ruby dependency from our front-end workflow.

**Comment by rightaway** [comment]
+1

**Comment by bigskinnyboy** [comment]
The latest version 2.2.2.alpha.1 does support libsass so this can probably be closed.
