### ISSUE TITLE
Expected 'in' keyword in @each directive

### ISSUE THREAD

**Issue by visualcookie** [ericam/susy#407]
Hi,

I manually "installed" Susy in a project. As soon as I call the susy.scss file I get an error in console.

Any ideas? Didn't changed anything just Drag & Dropped it into my projects folder.

**INFO:** I'm using LibSass. Could this be the problem?

![console-output](https://cloud.githubusercontent.com/assets/1857554/5232164/d5aafa52-7748-11e4-9072-10cf6a5e0a8d.jpg)

--
Dean Hidri

**Comment by HugoGiraudel** [comment]
I believe this comes from the fact that you were using an outdated version of Sass which did not support this version of the `@each` loop.
