### ISSUE TITLE
Susy Next?

### ISSUE THREAD

**Issue by rightaway** [ericam/susy#413]
At http://oddbird.net/2013/01/01/susy-next/ from almost 2 years ago it says that Singularity and Breakpoint were bothbeing merged into Susy Next. And on the issue tracker here I see people mentioning a Susy Next branch. But I don't see such a branch, and the Singularity and Breakpoint projects seem to be still active. And at https://github.com/at-import/Singularity/issues/154 it says that Singularity isn't being stopped after all. Just wanted to know what happened to Susy Next as I'm trying to make a decision between one of the various grid systems out there.

**Comment by rctneil** [comment]
Susy Next IS the current version of Susy. Susy 2. It's awesome too!

**Comment by ericam** [comment]
We went ahead with the merge of features, but they decided not to drop their own projects. So Susy 2.0 == Susy Next, with many old Singularity features, and new integrations for Breakpoint. But Singularity continues to exist separately.
