### ISSUE TITLE
Libsass and Grunt

### ISSUE THREAD

**Issue by rctneil** [ericam/susy#417]
I'm trying to get my Susy powered site compiled using LibSass. I have tried installing Susy via Bower and importing into my stylesheet and also tried installing via npm and using require but both ways and any variations I try cannot seem to locate susy correctly.

Is there a recommendation on how to get Susy compiling correctly.

My application is a Rails based one but I have entirely disabled the asset pipeline and am doing all my build process using Grunt. I have a task set up for grunt-sass and would like to use this as, if I am not mistaken this is LibSass and not Ruby Sass (correct?).

Any ideas?

**Comment by ericam** [comment]
Sounds like you have the basics in place, grunt-sass should work for you. There are different options for getting the import right. You can either dig around in the grunt-sass/node-sass settings to add an import path (I'm not sure on the specifics, but I think there's an option), or manually hard-code the import path to the susy files. That might look something like: `@import "../../bower_components/susy/sass/susy";` Notice that you can't just import the Susy root directory. Does that match what you have already?

**Comment by rctneil** [comment]
Perfect. Just required a tweak of my import to this:

    @import "public/assets/bower-components/susy/sass/susy";

Working through rest of the errors as I have removed Compass and replacing it with Bourbon which is causing it's own errors. Hopefully I can get them all resolved soon.

Thanks
