### ISSUE TITLE
Errors when running 2.2.1 via Node and grunt

### ISSUE THREAD

**Issue by danny-englander** [ericam/susy#420]
I am getting an error when I run grunt:

```
Warning: /gratis/node_modules/susy/pkg/susy-2.2.1/sass/susy/language/susy:7: file to import not found or unreadable: "../output/float"
```
In my main styles.scss file I have:

```
@import "../node_modules/susy/pkg/susy-2.2.1/sass/susy"; 
```
That file in turn points to 

```
@import 'susy/language/susy';
```

When you open that file, there indeed seem to be some broken file references. For example ```@import "../output/float";``` has a red underline in my IDE meaning it can't be found. If I comment out the offending line, it goes to further errors of other files that can't be found, ```@import "susy/grids";```

Note, I deleted the old node susy folder and reran ```sudo npm install```. My package.json file has: 

```
"susy": "^2.2.0"
```

So I am not sure if I am doing something wrong here or if this is a valid error. I was running an RC version a few days ago and it was fine, I did not get these errors.

**Comment by ericam** [comment]
Looks to me like that npm package is all wrong. Try `npm install susy@beta` and then `@import "npm_modules/susy/sass/susy";` — let me know if that works, and I'll release it again properly.

**Comment by danny-englander** [comment]
Hi Eric, thanks that worked great, I ended up using:

```
sudo npm install --save-dev susy@beta
```
and package.json now has ```"susy": "^2.2.2-alpha.1"```

Running grunt thereafter compiles susy (in a split second of course! :)
