### ISSUE TITLE
Susy settings error

### ISSUE THREAD

**Issue by AndyNhi** [ericam/susy#421]
I am trying to change the default susy settings for gutter; however I get the following error message in my terminal. Please help and thank you. 

app.scss

```
@import 'reset';

$susy: (
columns: 12,
gutters: 1/4,
math: fluid,
output: float,
gutter-position: inside,
);

```

terminal
```
File: /Users/andynguyen/workspace_ember/css_portfolio/tmp/tree_merger-tmp_dest_dir-rgJoel9Z.tmp/app/styles/app.scss (69)
may only co
```

**Comment by ericam** [comment]
LibSass had a bug with comparing fractions. If you can't upgrade to a newer version of LibSass, try adding `()` around your fractions (eg `gutters: (1/4),`).

**Comment by AndyNhi** [comment]
perfect thank you @ericam
