### ISSUE TITLE
Odd spacing in CSS Output (LibSass)

### ISSUE THREAD

**Issue by danny-englander** [ericam/susy#422]
I am using grunt-sass and Susy and noticed odd spacing with something like this:

```
.one-sidebar.sidebar-second {
    .l-content {
      @include span(17 of 24);
      @include bleed(0 2% 0 0);
    }
  }
```

Output:

```
 .one-sidebar.sidebar-second .l-content {
    
    
    
    width: 70.5882352941%;
    float: left;
    
    margin-right: 0.8403361345%;
    
    
    
    margin-right: -2%;
    
    
    
    padding-right: 2%;}
```

None of my other CSS outputs like this, it seems to be specific to Susy. I guess I may need to create a reduced test case as I have a lot of node modules in play. Let me know if that would be advised or if this is something that might ring a bell.

**Comment by ericam** [comment]
I've seen similar. This is a Libsass bug, and doesn't happen at all in Ruby Sass. There is no *correct* way to tell Sass how things should be spaced - so any attempted solution on our end would be a hack. I recommend filing an issue (if there isn't one already) against the libsass project.

**Comment by danny-englander** [comment]
Ok great, thanks, I will check that out!
