### ISSUE TITLE
Debug mode got error when use default gutters value

### ISSUE THREAD

**Issue by suisho** [ericam/susy#430]
I set above setting, and got error.

```scss
$susy: (
    columns: 12,
    debug: (
      image: true,
      output : background
    )
  );
```

```
Error: argument `$value` of `percentage($value)` must be a number
Backtrace:
	scss/susy/susy/language/susy/_background.scss:157, in function `percentage`
	scss/susy/susy/language/susy/_background.scss:157, in function `get-background-sym`
	scss/susy/susy/language/susy/_background.scss:337, in function `if`
	scss/susy/susy/language/susy/_background.scss:337, in function `get-background`
	scss/susy/susy/language/susy/_background.scss:39, in mixin `background-grid`
	scss/susy/susy/language/susy/_background.scss:21, in mixin `show-grid`
	scss/susy/susy/language/susy/_container.scss:26, in mixin `container`
	scss/grid.scss:38
```
And I fix `$susy` value, error is solved.

```scss
$susy: (
    columns: 12,
    gutters : .25,
    debug: (
      image: true,
      output : background
    )
  );
```

In the document, `gutter` has default value, but this look like not use default value. 
Is this bug? or If this specification? 
(If this is spec, I want add to document this :smiley:

**Comment by ericam** [comment]
This is likely a libsass error. Are you using some version of node-sass, grunt-sass, or gulp-sass?

Looks like our default `gutter` setting is a fraction, and older versions of libsass had trouble with fractions. They've fixed the bug, but unfortunately that change has not trickled down node-/grunt-/gulp-sass. We should change the default just to be safe.

**Comment by suisho** [comment]
yes, I got this error with grunt-contrib-sass.

**Comment by cibulka** [comment]
Same here, I'm using [Grunt-Sass](https://github.com/sindresorhus/grunt-sass) - Grunt plugin for (node-sass)[https://github.com/sass/node-sass]. Could you change Susy's default configuration for gutters from 1/4 to 0.25 to prevent that? 

Thanks again for awesome Susy!
