### ISSUE TITLE
Switching to libsass using Grunt

### ISSUE THREAD

**Issue by StudioMomentum** [ericam/susy#431]
I've been using susy with grunt. After seeing the release of susy 2.2.2 with libsass support I went straight to setting it up but I can't get it running. 

I've seen other problems people have had, mainly due to @include path. When I first ran grunt with the grunt-sass, susy set-up I didn't change the import path so I got errors saying that the file couldn't be found. I changed the import path to go direct to susy in my projects node_modules folder. I ran my grunt task again and instead of getting the previous error of 'no file found' I got an 'invalid property' error. 

I'm a bit stuck here as It seems like the correct path is in place due to the no file found error going away, but the susy file doesn't seem to be loading as mixins aren't there.

I have grunt, sass, libsass and susy in their latest version the sass task is as the susy documentation.

Is there anything else other than the import path that I could be getting wrong?

**Comment by ericam** [comment]
Can you paste in the relevant bits of code, and file structure? It's hard to comment in the abstract.

**Comment by StudioMomentum** [comment]
Apologies, was late and in a rush. 
Sure, of course.

##### My Gruntfile sass task

    `sass: {
        compile: {
            options: {
                require: 'susy',
                style: 'expanded',
                sourcemap: 'none',
                loadPath: require( 'node-bourbon' ).includePaths
            },
            files: [{
                'style.css': 'style.scss',
            }]
        }
    }`

##### My package.json 

  `"devDependencies": {
    "grunt": "~0.4.5",
    "grunt-sass": "~0.17.0",
    "susy": "^2.2.2-alpha.1"
  },`

##### File structure

/node_modules/susy
/node_modules/grunt-sass
/sass/_partials.scss
style.scss
style.css

**Comment by ericam** [comment]
ok, I'm not a Grunt expert by any means, but that all makes sense to me (though you could upgrade to the 2.2.2 stable release if you want). What does you include line look like, and what's the full error message?

**Comment by StudioMomentum** [comment]
Unfortunately neither am I.
And thanks, I planned to upgrade asap.

##### Import path in style.scss and the following is in _partials.scss

`@import 'node_modules/susy/sass/susy';`
`@import '../node_modules/susy/sass/susy';`

I can't re-create the error right now, but compiling throws an error at the first `@mixin`it gets too. I've taken that particular mix-in out to test, and it just throws an error on the next `@mixin` it finds. The error is 'invalid property'.

**Comment by ellm** [comment]
Works great for me. I'm using latest 2.2.2 and Grunt Sass 0.17.0. 

I believe `../node_modules/susy/sass/susy` should be the correct file path based on your directory structure above. So you should remove that first @import in your _partials.scss

**Comment by StudioMomentum** [comment]
Thanks for your input @ellm. I've no doubt that the build works perfectly. I've tried everything except starting from scratch which I can't do right now, I assume there is something in my set-up causing this issue now. 

Thanks @ericam

**Comment by danny-englander** [comment]
I noticed that you are using "loadPath" for Bourbon whereas LibSass uses "includePaths".  That could also be one of the culprits for errors if you are still getting them. 

e.g.
```
includePaths: require('node-bourbon').includePaths
```

**Comment by j-mccarthy** [comment]
Thanks Danny, I changed "loadPath" to "includePaths" but still the same thing happens. I know I have the correct paths in my .scss files. I'll report my solution when I get the time to find one.
