### ISSUE TITLE
utilities.scss error on compile

### ISSUE THREAD

**Issue by smguy** [ericam/susy#435]
I'm using compass and installed the Susy SCSS files manually. I'm running into the error below when compiling. It's centered around line 78 of the utilities.scss file.

What exactly am I missing here that's causing this error out of the box?

ERROR:
error sass/screen.scss (Line 78 of sass/susy/language/../su/_utilities.scss: Invalid CSS after "    @each $key": expected "in", was ", $value in $ma...")

**Comment by simonpay** [comment]
Did you find a solution to this? I have a very similar problem but on line 58 of susy utilities.scss.

error src/scss/app.scss (Line 58 of bower_components/susy/sass/susy/su/_utilities.scss: Invalid CSS after "...merge: ($_merge": expected ")", was ": $_value);")

**Comment by smguy** [comment]
Yea, I was essentially needing to upgrade my version of compass to 3.4.1
The version I had been using only supported the legacy version of SUSY.

**Comment by simonpay** [comment]
Thanks - worked a treat!

**Comment by HugoGiraudel** [comment]
It happened because you were using Sass 3.2 which did not support this version of the `@each` loop. Glad it is fixed. :)
