### ISSUE TITLE
Negative margin mixin solution

### ISSUE THREAD

**Issue by gabormeszoly** [ericam/susy#437]
Hi,
Any mixin solution for negative margin with gutter? Like a `@include pad(1 of 12);`

pad(1 of 12) output is:
`padding-left: 5.6603773585%;`
`padding-right: 5.6603773585%;`

solution needed with:
`margin-left: -5.6603773585%;`
`margin-right: -5.6603773585%;`

Thanks, Gabor

**Comment by ericam** [comment]
No special mixin needed - this just works:

```scss
.negative-padding {
  @include pad(-1 of 12);
}
```

**Comment by gabormeszoly** [comment]
Hello Eric,
Thanks for your answare, but the negative padding is an invalid property.
What do you think about this solution: http://codepen.io/gabormeszoly/pen/VYxLWY
Thanks, Gabor

**Comment by ericam** [comment]
I think you are looking for `squish(-1 of 6);` maybe? You need to pass in the context to get the correct relative math.

**Comment by gabormeszoly** [comment]
I see :) Thanks for your time again!
