### ISSUE TITLE
Using Susy in Grunt without Compass

### ISSUE THREAD

**Issue by 4Digits** [ericam/susy#438]
Is it possible to use Susy via Bower with grunt-contrib-sass?

https://github.com/gruntjs/grunt-contrib-sass

**Comment by ericam** [comment]
Yes, absolutely. I don't know much about the `grunt-contrib-sass` end of things, but once you install Susy (with bower in your case), it's nothing but a bunch of Sass files — you can import it like any other Sass files.

**Comment by 4Digits** [comment]
Thanks for your quick response. Trying to set it up and I constantly get an error with the imports:

`Error: File to import not found or unreadable: bower_components/susy/sass/susy/_susy.scss.
       Load path: /var/www/html/project`

All my other partials are importing without problems.

**Comment by 4Digits** [comment]
Problem solved; there was a typo in the correct path. Works like a charm with grunt-contrib-sass. 
Maybe the documentation should be updated accordingly as many developers are now using Libsass and grunt-contrib-sass...
