### ISSUE TITLE
Invalid css with grunt-sass (at-root issue)

### ISSUE THREAD

**Issue by SasSam** [ericam/susy#439]
Hi,

Susy is amazing and thanks for that! But could you please support `grunt-sass`? Because I need to use it but it's generating invalid css code, because `@at-root` is not compiled from `@mixin overlay-grid()` as not supported by `libsass` (as I know).

Thanks!

**Comment by ericam** [comment]
We do already support `grunt-sass` — more accurately, they finally support us. :) The overlay-grid is one of the very few features they don't yet support. There's not much we can do about that from our end, but it shouldn't keep you from using Susy. Use the background grid instead - or roll your own overlay by putting the background on generated content.

**Comment by brunowego** [comment]
+1

**Comment by HugoGiraudel** [comment]
Is this issue still relevant?
