### ISSUE TITLE
box-sizing mixing is deprecated in Bourbon

### ISSUE THREAD

**Issue by RAFA3L** [ericam/susy#442]
from line 12 of bower_components/susy/sass/susy/output/support/_box-sizing.scss

For now I must change by hand

@include box-sizing($model);

to 

box-sizing: $model;

**Comment by ericam** [comment]
That's why we have settings to turn off/on external integrations:

```scss
$susy: (
  use-custom: (
    box-sizing: false
  )
);
```

You can see the other integration settings in [the docs](http://susydocs.oddbird.net/en/latest/settings/#global-defaults).

**Comment by RAFA3L** [comment]
Thanks!
