### ISSUE TITLE
Grid position (at) in span mixin

### ISSUE THREAD

**Issue by lmartins** [ericam/susy#444]
Im having problems trying to have the "at" attribute passed to `span` mixin. For some reason I can't get it to work reliably.

Considering the following code:

```sass
$grid: (1 2 2 2 2 1);
.article-content{
    @include container(show $grid);
}
.article-body{
    @include span(4 of $grid at 2);
}
```

Am I missing something here?
The weird thing about this is that I had this code, or very similar, working before so Im not sure what's going on.

I should also point out im using Libsass.

**Comment by ericam** [comment]
Hard to know what problem you are having from this. What output are you getting, and what output are you expecting?

One point of confusion for people is that `at` does not actually *reposition* your element, unless you are using `isolation`. In this case, `at` is simply being used to get the proper grid-span width.

**Comment by lmartins** [comment]
sorry, i've should had been clearer on this.
From the docs I got the impression `at` could be used with or without `isolation`, so most likely this is not an issue but a misunderstanding on my part.

Thanks for tip Eric.

**Comment by lmartins** [comment]
And indeed my mistake. Love `isolation`grids :)

**Comment by ericam** [comment]
`at` can be used without isolation, but only for _selecting_ the right columns from an asymmetric grid - not for actual positioning. That's because positioning is relative, and only isolation guarantees that we have a consistent edge to push off.
