### ISSUE TITLE
Nested grid with wide and no-gutter option calculates the wrong child sizes

### ISSUE THREAD

**Issue by ntiedt** [ericam/susy#446]
You can see my code here -> http://sassmeister.com/gist/bf95b013dfad5977511c.

The problem is that i want 4 same cols but the left 3 are in 1 container and the single on the right have its own box.

.content_main{
                @include span(15 wide of 20 no-gutter);
                .span_1_3{
                    @include span(5 of 15);
                }
}

I need the extra space with 15 wide of 20 no-gutter because i want to have that the childs have the normal gutter of my 24 grid on right side.

But it seems susy calc with false values.
As you can see my gist the 3. child is wrapped to next line.
If i replace "15 wide of 20 no-gutter" to "15 of 20 no-gutter" the calc is correct.
But there is not enough space for the childs.

How can i fix this or maybe it´s a bug?

**Comment by ericam** [comment]
It doesn't work because the context for those children is not actually 15-columns — so `span(5 of 15)` is not accurate. I assume the reason you want gutters on the children rather than the parent is so you don't have to remove gutters from the last child in each row?

I'd recommend letting Susy handle that automatically with the `gallery` mixin:

```scss
.span_1_3 {
  @include gallery(5 of 15);
}
```

**Comment by ntiedt** [comment]
Thanks for your answer.
Yes you are right. I want that the childs have the gutters.
The problem with gallery is that it use margin to do the positioning.
But I didn´t want because if I resize the browser window to e.g. 1024 width the child should be first 3 in a row and with smaller window 2 and so on.
With a normal float much easier and much less code.
But I will use the gallery.

Anyway I must say your Toolkit is incredible and i will never miss it.
Thanks for your hard work – keep it up.

**Comment by ericam** [comment]
You can change your gallery at different breakpoints to get the effect you need. It is more output code, but not enough to have any real impact on your performance.
