### ISSUE TITLE
Susy 2.2.2 / node-sass: Span(full) 

### ISSUE THREAD

**Issue by jonalviar** [ericam/susy#448]
Hi, I am not sure if this belongs here or in the node-sass repo. Currently I moved over to latest node-sass everything is working fine for the most part, but we get a error when we do this...

`@include span(full)` 
Error message: may only compare numbers

Now we actually have to define it by numbers, ex. 12 of 12, 6 of 12 for it to compile. Was this dropped in support or could possibly be a node-sass issue?

Thanks!

**Comment by ericam** [comment]
I was able to reproduce this, but we'll need to track it down. Likely a libsass bug, since it works fine in Ruby Sass.

**Comment by DenisMir** [comment]
The same error exists on my side. It would be awesome if the error can be found. :+1:

**Comment by jonalviar** [comment]
@DenisMir I confirm that if I wrap my gutters in ( ), I am able to use `@include span(full)` and I get no error.

**Comment by DenisMir** [comment]
With the latest `node-sass` version which uses `libsass` in version _3.2.0-beta.2_ I don't even need the `()` wrap around my gutters. But the main problem remains. The `span` mixin eats up all the compile performance. When dropping all the `span` calls I'm down at a 10-100ms (depending on the machine) but adding the `span` calls the compile time gets up to over 2 seconds.

**Comment by ericam** [comment]
Yes, that was a well-documented LibSass bug, that has been fixed. Cheers!
