### ISSUE TITLE
Gallery: % based span causes errors on compiling

### ISSUE THREAD

**Issue by christianmagill** [ericam/susy#449]
I updated my node_modules when moving to a new server and now I receive an error from gulp sass when using % based spans in gallery mixins.

This hasn't been a problem before update

 unterminated argument to :nth-child(...) on line 66 in ..../susy/sass/susy/language/susy/_gallery.scss

**Comment by ericam** [comment]
Updating from between what versions?

**Comment by christianmagill** [comment]
Unfortunately I am not sure, the problem persists in the current versions pulled through npm install for gulp-sass (1.3.3) and bower for susy (2.2.2).

**Comment by ericam** [comment]
This seems to be a Libsass bug that was fixed.
