### ISSUE TITLE
24 columns gutter size

### ISSUE THREAD

**Issue by wonderment** [ericam/susy#450]
Hello,

We're having some difficulty when it comes to using a higher column count such as 24 columns and the gutter results.

It's known increasing the column count by double will effectively cut the gutter size in half but given our normal gutters setting is .5, is there a cleaner method than simply increasing it to something dramatic such as gutters: 10? In tight, mobile spaces it reduces to below 1%.

Here's a codepen with a sample site header and the aforementioned settings in place: http://codepen.io/wndrmnt/pen/OPBoXj

We utilize the 24-column setup to allow finer control, just as a general FYI.

Thank you!

**Comment by ericam** [comment]
There are 2 solutions:

1. Change your column-count at smaller breakpoints.
2. Use `gutter-position: inside-static` to get gutters that don't resize at all. (You'll also need to set a `column-width` to make that work)

**Comment by wonderment** [comment]
Hi Eric,

The inside-static is a good pointer and we hadn't considered that and will give it a go. We assumed it is simply a matter of working *around* the 24 column-count given the math involved but wanted to confirm, anyway.

We really appreciate your hard work!

Thanks!
