### ISSUE TITLE
layout mixin not respecting media queries

### ISSUE THREAD

**Issue by sam-keen** [ericam/susy#451]
Hi there, I am finding that if I create a new layout within a media query, that it applies globally, ignoring the media query. Please take a look at this gist: http://sassmeister.com/gist/3fe35dfc99285e606968 

If the .main's styling is positioned in the cascade after the initial 12 col layout mixin but before the media query, it's width is the expected 100%. However if it's positioned after, and importantly OUTSIDE the media query, it is still recognising the 24 col layout and its width is changing to 50%. 

I would only expect the 50% width behaviour to happen if the .main's span was also inside the media query. 

Is this an error or am I misunderstanding how susy works?

Many thanks

**Comment by ericam** [comment]
It's a common confusion in Sass — and not something Susy has any control over. Sass variables are not scoped to media-queries unless they are created inside the media-query.

Susy does provide integration with breakpoint that will do what you are attempting:

```scss
@include layout(12);

@include susy-breakpoint (500px, 24 0) {
  .main {
    @include span(12);
  }
}

.main {
  @include span(12);
}
```

**Comment by sam-keen** [comment]
fantastic, thanks
