### ISSUE TITLE
Fixed menu causes grid to break in FireFox and IE

### ISSUE THREAD

**Issue by 4Digits** [ericam/susy#457]
I have a menu that is dynamically fixed with jQuery to the top when the window is scrolled down by 100px. In that case a "is-fixed" class is added to the menu. The content section is divided into a main column on the left (9) and a sidebar "aside" on the right (3). 

The problem now is that when I scroll down in FireFox, the grid layout of the main section is destroyed. The sidebar is pushed down the main section, while the main section is pushed to the side by 3 columns. In Chrome everything works fine. 

If I remove the "l-wrap" class from the main section (i.e. give the section a full width), I don't have the problem. The grid stays intact. However, I need to place the content in a centered container.

```
.is-fixed {
	position: fixed;
	top:0;
	left:0;
        width: 100%; 
       z-index: 998;
       background: #000;    
}
```

Grid:
```
/* susy */

$susy: (
  columns: 12,
  gutters: 1/4,
  math: fluid,
  output: float,
  gutter-position: after,
  debug: (
    image: show-columns,
    color: rgba(#66f, .25),
    output: overlay,
    toggle: top right,
  ),
);


/* wrapper */

.l-wrap {
	@include container(65em);	// 1170px (base 18px)
}

#main {
	padding: $container-padding;
	
	@include breakpoint($desktop-md) {
		@include span(9 of 12 first);
	}
}

aside {
	padding: $container-padding;
	
	@include breakpoint($desktop-md) {
		@include span(3 of 12 last);
	}
}
```

Any idea how to fix this?

**Comment by nickbullets** [comment]
You'll have a much better response (hopefully) if you provide an individual sample of your code via codepen or something of the likes. If you have the site live, that works, too. Tt'll be easier for someone to diagnose the problem for the former.

Generally, if you're experiencing problems in Firefox which is usually safe to cover from a support perspective, there are most likely issues in other browsers as well.

**Comment by ericam** [comment]
I can't recreate this issue with the code you've provided — and your code looks fine (as long as you are using `border-box` sizing). Can you provide a breaking demo to look at?

**Comment by 4Digits** [comment]
Here is a live demo:

http://bit.ly/1FMuVoD
