### ISSUE TITLE
Gallery Grid no gutters

### ISSUE THREAD

**Issue by miguelsneto** [ericam/susy#459]
I would like to create a gallery grid without gutters. Even with all the attempts did not succeed.

```
$map-portifolio: (
  gutters: 0
);
@include with-layout($map-portifolio) {
  .portfolio-item{
    @include gallery(3 of 12);
    overflow: hidden;
    padding: 0px;
    position: relative;
  }
}
```

**Comment by zellwk** [comment]
Just this would have worked. 
~~~
$map-portifolio: (
  gutters: 0
);

@include with-layout($map-portifolio) {
  .portfolio-item{
    @include gallery(3 of 12);
  }
}
~~~

Can you put it up on Codepen or Sassmeister for me to take a closer look?

**Comment by miguelsneto** [comment]
when I compile the way mentioned the following error appears:
```
error assets/sass/style.scss (Line 72 of /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/susy-2.2.2/sass/susy/language/susy/_isolate.scss: Invalid null operation: "25% plus null".)
Compilation failed in 1 files.
```

**Comment by zellwk** [comment]
That's interesting. An exact replica of the code works. 

http://sassmeister.com/gist/589c84a84954c01e9347

@ericam any ideas?

**Comment by ericam** [comment]
Seems to be a bug specifically related to `split` gutters — from these lines in Susy:

```scss
  @if susy-get(gutter-position, $input) == split {
    $width: if($width == null, gutters($input), $width + gutters($input));
  }
```

Clearly a bug we need to fix. In the meantime, you can use `gallery(3 of 12 inside);` (or add `inside` to your layout map) to get around the problem. Since there are no gutters, their position won't matter.

**Comment by miguelsneto** [comment]
OK. Is clearly not the ideal situation more solved my problem.
Could mark this issues with the label bug ?
