### ISSUE TITLE
Push and Pull

### ISSUE THREAD

**Issue by miguelsneto** [ericam/susy#460]
there is a way to pull and push with breakboint?
I have 3 columns in wide (5,3 and 4) and I want the first column is the latest in Mobile

http://sassmeister.com/gist/589c84a84954c01e9347

**Comment by ericam** [comment]
I don't know what you are asking for, but if you can do it with CSS, you can do it with Susy & Breakpoint. Susy provides both `push` and `pull` mixins — as well as functions to help you do your own math. Use those layout tools along with Breakpoint's media-queries, and you should be able to make it work.

**Comment by dsushmasagar** [comment]
When I applied push mixin on desktop resolution it works fine.  http://sassmeister.com/gist/00ab2ef69b57e3b803cf 
When try to apply the same thing in my mobile media query that was changing my desktop styles.
http://sassmeister.com/gist/0f686ecceadeec061e53.

Am I doing it in right way?
