### ISSUE TITLE
susy-breakpoint mixin wipes variables

### ISSUE THREAD

**Issue by mrpavlikov** [ericam/susy#462]
Hello.

I am using susy installed via npm + libsass through gulp. Lets say I have 2 variables:

```scss
$mobile: 640px;
$tablet-only: 641px 1024px;
```

After I pass first one to `susy-breakpoint` its ok, but whenever I pass variable like second one it's being erased. I've prepared demo repo:

https://github.com/mrpavlikov/susy-bug

**Comment by ericam** [comment]
I can't recreate this: http://sassmeister.com/gist/c3e680f0eed7a24acb8d

**Comment by HugoGiraudel** [comment]
I cannot recreate this on my side either. Which version of Sass are you using? Are you able to set up a SassMeister with the minimum amount of code to reproduce it?

**Comment by ericam** [comment]
Closing until further updates.
