### ISSUE TITLE
Debug settings "image" not working w/ libsass?

### ISSUE THREAD

**Issue by jerseycheese** [ericam/susy#463]
Working on getting a Grunt build process going for Susy+Breakpoint via libsass (without Compass)... so for so good, but I'm finding that the debug image isn't being added to the container elements through `@include container;` - my container element is `#main`.

All that is compiled for the container is margin/width CSS:
```
#main {
  max-width: 100%;
  margin-left: auto;
  margin-right: auto;
}
```
Here is my settings config:
```
// At the moment, need to define these outside the grip layout maps below.
// https://github.com/ericam/susy/issues/408#issuecomment-76624637
$small_med_gutters: 20px/44px;
$large_wide_gutters: 20px/55px;

// Turn on/off debug images.
//$debug_image: hide;
$debug_image: show;

// Establish grid settings
$small: (
  debug: (
    image: $debug_image,
    color: rgba(black, .1),
    output: background,
  ),
  columns: 6,
  gutters: $small_med_gutters
);

$medium: (
  debug: (
    image: $debug_image,
    color: rgba(#66f, .1),
    output: background,
  ),
  columns: 12,
  gutters: $small_med_gutters
);

$large: (
  debug: (
    image: $debug_image,
    color: rgba(green, .1),
    output: background,
  ),
  columns: 12,
  gutters: $large_wide_gutters
);

$wide: (
  debug: (
    image: $debug_image,
    color: rgba(red, .1),
    output: background,
  ),
  columns: 16,
  gutters: $large_wide_gutters
);
```
And how I'm using column layouts:
```
.panel-two-sidebars {
  .panel-col {
    @include susy-breakpoint($breakpoint-medium-up, $medium) {
      @include span(6);
    }
  }
  .panel-col-first {
    @include susy-breakpoint($breakpoint-medium-up, $medium) {
      @include span(3);
      @include first;
    }
  }
  .panel-col-last {
    @include susy-breakpoint($breakpoint-medium-up, $medium) {
      @include span(3);
      @include last;
    }
  }
}
```

**Comment by lmartins** [comment]
You need to call the `show`argument when you define your containers:
```@include container(show)```

**Comment by jerseycheese** [comment]
Alright, I've added that but, I get this during compile...

```
Running "sass:dev" (sass) task
>> argument `$value` of `percentage($value)` must be a number
>> Backtrace:
>> 	bower_components/susy/sass/susy/language/susy/_background.scss:157, in function `percentage`
>> 	bower_components/susy/sass/susy/language/susy/_background.scss:157, in function `get-background-sym`
>> 	bower_components/susy/sass/susy/language/susy/_background.scss:337, in function `if`
>> 	bower_components/susy/sass/susy/language/susy/_background.scss:337, in function `get-background`
>> 	bower_components/susy/sass/susy/language/susy/_background.scss:39, in mixin `background-grid`
>> 	bower_components/susy/sass/susy/language/susy/_background.scss:21, in mixin `show-grid`
>> 	bower_components/susy/sass/susy/language/susy/_container.scss:26, in mixin `container`
>> 	sass/layouts/_responsive.scss:36
>>   Line 157  Column 21  bower_components/susy/sass/susy/language/susy/_background.scss
```
Line 36 of _responsive.scss is the @include at ...
```
#main {
  @include container(show);
}
```

**Comment by docmars** [comment]
@jerseycheese This error may be due to `libsass` not supporting fractions. By default, susy's `gutters` setting is set to 1/4. If you set it to 0.25, you should be good.

```sass
$susy: (
    gutters: 0.25
    // ...
);
```

See #430 for more details.

**Comment by michael-arvanitidis** [comment]
I'm having the same problem, but setting gutters to 0.25 instead of 1/4 and also calling @include container(show) did not solve it for me. When I look at the generated css for the overlay this is what I get

```
  background-image: -owg(compact(linear-gradient(to right, rgba(102, 102, 255, 0.25), rgba(179, 179, 255, 0.25) 80%, transparent 80%), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false));
  background-image: -webkit(compact(linear-gradient(to right, rgba(102, 102, 255, 0.25), rgba(179, 179, 255, 0.25) 80%, transparent 80%), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false));
  background-image: -moz(compact(linear-gradient(to right, rgba(102, 102, 255, 0.25), rgba(179, 179, 255, 0.25) 80%, transparent 80%), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false));
  background-image: -o(compact(linear-gradient(to right, rgba(102, 102, 255, 0.25), rgba(179, 179, 255, 0.25) 80%, transparent 80%), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false));
  background-image: compact(linear-gradient(to right, rgba(102, 102, 255, 0.25), rgba(179, 179, 255, 0.25) 80%, transparent 80%), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false);
```

which obviously don't render a background image.

**Comment by iainhouston** [comment]
Yes, there seems to be a conflict between "susy": "~2.2.5",   "breakpoint-sass": "~2.6.1",   "compass-mixins": "~1.0.2" and "gulp-sass": "^2.0.1",  that produces a `background-image` that browsers don't understand: 

      background-image: -owg(compact(linear-gradient(to right, blue, #4d4dff), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false));
      background-image: -webkit(compact(linear-gradient(to right, blue, #4d4dff), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false));
      background-image: -moz(compact(linear-gradient(to right, blue, #4d4dff), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false));
      background-image: -o(compact(linear-gradient(to right, blue, #4d4dff), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false));
      background-image: compact(linear-gradient(to right, blue, #4d4dff), linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 1px, transparent 1px), false, false, false, false, false, false, false, false);  

from   elements with `@include container(show);` and global susy settings: 

    $susy :(
      columns: 12, 
      container: 1140px, 
      gutter-position: inside,
      global-box-sizing:  border-box, 
      debug: (image: hide, color: blue)
    );

**Comment by zellwk** [comment]
@jerseycheese 

You'll need to use either the `container()` mixin or `show-grid()` mixin in order to make the grid show up. Check this tutorial out: http://www.zell-weekeat.com/susy-grid-background-image/

Note: You'll also need to make sure gutters are provided and is either a fraction wrapped in parenthesis, or a decimal, like `(20px/40px)` or `0.25`. 

@michael-arvanitidis background image code looks good to go. did you remember to use either the `container()` mixin or `show-grid()` mixin? 

@iainhouston You'll need to make sure debug image is set to show. 

~~~
$susy: (
  debug: (image: show))
);
~~~

**Comment by iainhouston** [comment]
@zellwk as you can see in my OP, I prefer the global susy settings to be `debug: (image: hide)`  and then the individual element `@include container(show);` This was not the problem.

I have updated my post to show the solution in my situation.

**Comment by michael-arvanitidis** [comment]
@zellwk the problem is that the css for the background image is not understood by the browser. When I hover the debug toggler, the css for the background image is the one I posted in my previous comment. It's the generated css that is wrong, see this screenshot http://puu.sh/iprOn/65adeb985e.png

**Comment by zellwk** [comment]
@michael-arvanitidis Intereresting. It might be the case where @iainhouston mentioned above, that there's an error with the integration between Compass and Susy, especially with background-image.

Try what @iainhouston did, with background-image: false. 

$susy :(
  use-custom: (
    background-image: false,
    )
  );

**Comment by michael-arvanitidis** [comment]
@zellwk , @iainhouston 's fix worked great. Thanks :)
