### ISSUE TITLE
breakpoint and susy-breakpoint mixins create `@media and` -- re: #410

### ISSUE THREAD

**Issue by vongoh** [ericam/susy#467]
In reference to closed issue #410 -  am now having this same issue using this setup:

- grunt-sass ^0.17.0
- susy 2.2.2
- breakpoint-sass 2.5.0

For example: 
~~~
// SCSS
.l-content {
    @include span(4);

    @include breakpoint(768px) {
        @include span(3 of 4);
    }
}

// CSS output
.l-content {
    width: 100%;
    float: left;
    margin-left: 0;
    margin-right: 0;
}

@media and (min-width: 768px) {
    .l-content {
        width: 73.6842105263%;
        float: left;
        margin-right: 5.2631578947%;
    }
}
~~~

There's that extra `and` again in the output, its killing the media queries.   I'm a bit out of my depth here, but I looked at the fix in 4d92468 and compared it to what is in the `_breakpoint-plugin.scss` in my 2.2.2 install  - and the code does not match:

~~~
// What I am seeing in your 4d92468 fix .. 
 $no-query: false
) { 
@if susy-support(breakpoint, (mixin: breakpoint), $warn: false) {
     @include breakpoint($query, $no-query) {
         @content;
     }
} @else {
    @media #{susy-build-breakpoint($query)} {
        @content;

// What is in 2.2.2, relevant bits .. 
  $no-query: $susy-media-fallback
) {
  @if susy-support(breakpoint, (mixin: breakpoint), $warn: false) {
    @include breakpoint($query, $no-query) {
      @content;
    }
  } @else {
    @include susy-media($query, $no-query) {
      @content;
~~~

Its different - currently I do not have the shkeelz to analyse this.  Is there any other reason this might be happening?  Is there a different version chain ala libass/susy/breakpoint that is currently working?  thanks man!

**Comment by ericam** [comment]
That output is coming directly from Breakpoint. Susy is not even part of the equation. Looks to me like it has been fixed on their end.

Susy does look for breakpoint, and provide a fallback *if you use the `susy-breakpoint()` mixin` - but the `breakpoint()` mixin is direct from their plugin.
