### ISSUE TITLE
Can @import 'susy' work without specific pathing?

### ISSUE THREAD

**Issue by thedamon** [ericam/susy#470]
I have a grunt setup based on the yeoman webapp generator.

I followed the instructions to install Susy with bower but always get the `Error: File to import not found or unreadable: susy` if I have `@import "susy"` in my main.scss as suggested by the docs.

I can make it work if I write the full path:
@import "../components/susy/sass/_susy.scss";

And that's great! but I'm perplexed about how/when the line that's written in the documentation would work... or is it just shorthand and I'm assuming there's more magic in the world than there really is?

**Comment by zellwk** [comment]
@import "susy" works if you use the Susy ruby gem. Otherwise, you'll have to specify the path to Susy.

**Comment by ericam** [comment]
That's mostly true, but it's technically a bit more complex: `@import susy` works if you are using any sort of sass-aware package management — like compass. That should be available on libsass soon, using [eyeglass](https://github.com/sass-eyeglass/eyeglass).
