### ISSUE TITLE
wrong padding on inside-static

### ISSUE THREAD

**Issue by headione** [ericam/susy#475]
I try to enable a grid with static gutters and the following setup:

```$susy: (columns: 12, column-width: 70, gutters: 3 / 7, gutter-position: inside-static, container: 1170);```

The problem is, that the paddings in the output have no 'px' units, so the browser doesn't interprets it right. Is there a solution for this? Thank you.

output:

```
  padding-left: 15;
  padding-right: 15;
```

**Comment by zellwk** [comment]
You'll need to give the Units to column-width. (70px) for example. 




Likewise for container(1170px)




Stay Awesome! 
Zell

**Comment by headione** [comment]
thanks, i also tried that but then i got an error: 

```error app/styles/main.scss (Line 246 of app/styles/_style.scss: Incompatible units: 'px' and '%'.)```

**Comment by ericam** [comment]
What settings did you use, and what is at line 246 of `app/styles/_style.scss`?

**Comment by headione** [comment]
Now i have:

```$susy: (columns: 12, column-width: 70px, gutters: 3 / 7, gutter-position: inside-static, container: 1170px);```

**Comment by ericam** [comment]
Glad you got it sorted out. Cheers!
