### ISSUE TITLE
Remove percentage on Pad/Squish with 0 value 

### ISSUE THREAD

**Issue by peterankelein** [ericam/susy#476]
If I write something like:

```.padtest {
  @include pad(0); 
}```

or

```.margintest {
  @include squish(0); 
}```

...it returns 0% rather than just 0, which is preferred, no?

**Comment by ericam** [comment]
This isn't simple from a framework standpoint. We'd basically have to parse all our math output, looking for zeros and removing their units — probably a significant hit on compile time. That sounds like fun to me, but I'm not sure it's worth the effort for this. The only reason to the prefer unitless zero is simplicity, right? Is there any actual downside to leaving the units alone? I'm open to opinions here.

**Comment by anEffingChamp** [comment]
Best practices may recommend unitless zero, but I would argue that that 
falls to the developer to manage. If it is at all convenient for susy, then by 
all means remove those units. If not though, susy should be consistent 
more than any thing else.

**Comment by anEffingChamp** [comment]
Before I say that though, I should ask for a better sense of the trade off. How much might compile time increase for something that a crafted string replacement can fix?

**Comment by peterankelein** [comment]
While a unitless zero would be preferred, I think the only benefit is it saves a few bytes in the output but definitely not worth the effort if it affects compile time and is a huge amount of work. It's not a big deal to do a find and replace or for the two mixins mentioned write out manually (two lines as opposed to one). Just something that caught my eye on a current project.
