### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by jakob-e** [ericam/susy#482]
This is just an idea to prevent namespace conflicts with other frameworks/tools
(I just had one with isolate) – while waiting for namespaces to be part of Sass. 

1. All functions are prefixed with a unlikely-to-collide-prefix e.g.  \__s_u_s_y__
2. A _susy.namespace.scss file is added – mapping the prefixed functions/mixins to their current names

````` SCSS
//
// _grids.scss 
// 
@mixin    __s_u_s_y__layout($layout, $clean: false){ ...; }
@mixin    __s_u_s_y__with-layout($layout, $clean: false) { ...; } 
@function __s_u_s_y__with-layout($layout: $susy){ @return ...; }

// 
// _susy.namespace.scss 
//
// "exposed" name                 mapped name
@mixin layout($arglist...)      { @include __s_u_s_y__layout($arglist...); }
@mixin with-layout($arglist...) { @include __s_u_s_y__with-layout($arglist...); }
@function layout($arglist...)   { @return  __s_u_s_y__with-layout($arglist...); } 

`````
Now if I get a conflict with another library I can easily re-map `__s_u_s_y__isolate` to `susy-isolate` or whatever – without breaking any internal use.

**Comment by ericam** [comment]
That's a really interesting proposal. It would be easy to make backwards-compatible for most users, but I wonder if there are edge-cases worth considering. In either case, this is worth considering for our next major release. I would probably go with the simpler `susy-` prefixing from the start, and then remove the namespacing by default.

**Comment by jakob-e** [comment]
I think the susy- prefix for public functions and _susy- for private will suffice.

Here is a little sketch of a collision-detect mixin* to be included upon import
http://sassmeister.com/gist/2cfc6b7de2ce8591cffb

You could also use this to do an auto re-map – but that might be a little confusing 

\* to avoid adding more variables to the global namespace.
````SCSS
// 
//  Namespace Collision Detection
//
@function span(){ /* This is not susy */ }
@function last(){ /* This is not susy */ }
@mixin span(){    /* This is not susy */ }

// === Susy get's imported here ===
@mixin _susy-collision-detect {
  //
  // What needs testing
  // Note! alpha will always collide as it is now part of core Sass 
  //
  $test-collisions:(
    'span', 'gutter', 'container', 'nested', 'global-box-sizing', 'box-sizing',
    'break', 'nobreak', 'first', 'alpha', 'last', 'omega', 'pre', 'push'
  );
  
  //
  // Look for mixins or functions
  //
  $found-collisions:'';
  @for $i from 1 through length($test-collisions){
    $name: nth($test-collisions, $i);
    @if mixin-exists($name){ 
      $found-collisions: $found-collisions + '\A\2022  #{$name} (mixin)';
    }
    @if function-exists($name){ 
      $found-collisions: $found-collisions + '\A\2022  #{$name} (function)';
    }
  }
  
  //
  // Show warning/throw error  
  //
  @if length($found-collisions){
    @error('Susy says – we seems to have collisions on the following items:\A#{ $found-collisions }\A\A Please re-map....');
  }
}
@include _susy-collision-detect;

//
//  This is not found as it comes after 
//
@function first(){ /* This is not susy */ }

**Comment by HugoGiraudel** [comment]
Please keep in mind that Sass 4 is going to bring namespacing on the table, to the point where any custom solution might or might not be acting against Sass own namespacing system. Just something to remember. ;)

**Comment by HugoGiraudel** [comment]
Won't be done in v2 unless we run in some serious issues. Will be done in v3 though. :)

**Comment by jakob-e** [comment]
@HugoGiraudel :+1: gotta love how Sass evolves :-)
