### ISSUE TITLE
Cannot get the overlay toggle to change position (libsass 3.2)

### ISSUE THREAD

**Issue by PJL101** [ericam/susy#483]
Hi,

I am using Libsass 3.2 and I can't get the overlay toggle to change position and I believe it is a bug. I have created a simplified SassMeister example. My real code uses sass-mq but turning it off doesn't seem to affect this.

http://sassmeister.com/gist/953de2595e99c3807f34

Thanks,
Phil

**Comment by ericam** [comment]
This seems to work fine if you define the location in Susy's default `$susy` settings map. Only broken when you pass a new settings map directly to the mixin. I'll keep digging...

**Comment by ericam** [comment]
This should be fixed by 97e523f and released in version `2.2.5`. Let me know if you're still having issues!

**Comment by PJL101** [comment]
Wonderful, thanks for taking a look so quickly. NPM hasn't picked up the new version yet but when it changes I will test.

**Comment by ericam** [comment]
Odd, I installed it from npm right away. https://www.npmjs.com/package/susy

**Comment by PJL101** [comment]
Sorry I edited by comment straight after posting. I was in the wrong project.

**Comment by ericam** [comment]
oh, ha. I see. :) Great!
