### ISSUE TITLE
$base-line-height variable conflict

### ISSUE THREAD

**Issue by krzkrzkrz** [ericam/susy#484]
$base-line-height is also defined by default in Bourbon's Bitters. Maybe prefixing variables is the way to go to avoid conflicts?

It is located at https://github.com/thoughtbot/bitters/blob/master/app/assets/stylesheets/_variables.scss#L9

When the grid shows, it only displays one purple column.

**Comment by ericam** [comment]
This was an attempt at Compass integration, so we didn't name that variable. Clearly we need to be smarter about looking for it, though. Simplest fix might be to make sure the value of `$base-line-height` has units attached — and ignore it otherwise.

**Comment by krzkrzkrz** [comment]
Yea that sounds reasonable. In the meantime, I've just renamed the local variable (in Bitters) to something else
