### ISSUE TITLE
Using custom Rem to true duplicates the output

### ISSUE THREAD

**Issue by mesnitu** [ericam/susy#487]
Hi 
Not sure why this is happening, or am I doing something wrong in the grid config, but if I use :
 use-custom: (
    rem: true,
  )
@include container();

The css outputs : 
max-width: 100%;
  max-width: 100%;
  margin-left: auto;
  margin-left: auto;
  margin-right: auto;
  margin-right: auto;

Why is it duplicating ? 
Thanks

**Comment by ericam** [comment]
Hard to say, since you are telling Susy to use a custom `rem()` mixin — and I don't know what that mixin looks like. Are you using Compass? If so, that could be a bug in the Compass rem mixin.

**Comment by mesnitu** [comment]
hi
Ups, there was a custom mixing that I already forgot about. Now that I removed it, it's no longer duplicating. 
However, now, nothing happens, or, I still don't understand the use of this config. 
In the doc, says that will use compass if available. I'm using compass, with the vertical ryhthm config, base line, use rem, etc...  
So, does, Susy get's that config, or there's something else I need to do ?
thanks

**Comment by ericam** [comment]
I can't recreate this.

**Comment by ericam** [comment]
Closing for now. We can re-open if there are more updates.
