### ISSUE TITLE
Netbeans and Susy 2

### ISSUE THREAD

**Issue by webmasterpf** [ericam/susy#489]
Hi,

I don't find infos about using Susy 2 in Netbeans.
Actually i get issues on the map settings and when i change the map for gutters size like this:
```
@include breakpoint ($desktop){
           @include span(4 of $desktopcol (gutter-override:.5em));
        
        }
```
does exist a plugin or way to get netbeans doesn't waring me about the code instead of the code works..?

thanks

**Comment by HugoGiraudel** [comment]
Hello. 

Netbeans being an IDE, I am not sure how this would be any related to Susy itself. Is Netbeans running Sass inside its own view? If yes, which compiler does it use? Do you have some version numbers? 

I hardly think this is an issue with Netbeans, and go as far as saying there is a problem with your code and/or what you are trying to do. :)

**Comment by ericam** [comment]
Closing for now. We can re-open if there are more updates.

**Comment by webmasterpf** [comment]
this is what is looking in netbeans, no error mentionned but color syntax doesn't work.

![bug map susy2 - netbeans ide 8 0](https://cloud.githubusercontent.com/assets/157527/9678527/8f78adc0-52e6-11e5-9f7f-016040626e97.png)

**Comment by webmasterpf** [comment]
Comparison with sublime text: 
![bug map susy2 - sublime text 2](https://cloud.githubusercontent.com/assets/157527/9678952/88ca216c-52ea-11e5-8944-3775f0b3dec4.png)

**Comment by HugoGiraudel** [comment]
Susy has nothing to do with this. It is up to the syntax highlighter plugin used by the software.

**Comment by webmasterpf** [comment]
i agree, but is my code get an error ? because it's my first drupal theme with susy and if all seem to work this syntax "alert" insinuates doubt.

**Comment by ericam** [comment]
Your code looks fine. If you did have a syntax error, that would still be related to Sass more than Susy — and the parser would warn you.

**Comment by webmasterpf** [comment]
ok it's a good news for me ;) thanks
