### ISSUE TITLE
Simple way using with-layout

### ISSUE THREAD

**Issue by rizqinizamil** [ericam/susy#491]
I have 2 susy maps:
<pre>
$susy: (
  columns: 16,
  gutters: (30/43),
  container: 1140px,
  gutter-position: after,
);

$susy-small: (
  columns: 4,
  gutters: (1/4),
  container: 640px,
  gutter-position: split
);
</pre>

When I want to use <code>$susy-small</code> I have to write like this:
<pre>
@include breakpoint($small-range){
	@include with-layout($susy-small){
		@include span(4);
	} 
}
</pre>

Is there any simple way to do that?
I hope I can do like this:
<pre>
.container{
	@include container($susy);
	@include breakpoint($small-range){
		@include container($susy-small);
	}
}
</pre>

Thanks.

**Comment by ericam** [comment]
Sure can. See [susy-breakpoint](http://susydocs.oddbird.net/en/latest/toolkit/#breakpoint). Works with or without the breakpoint plugin:

```scss
.container{
    @include container;
    @include susy-breakpoint($small-range, $susy-small){
        @include container;
    }
}
```

**Comment by rizqinizamil** [comment]
Thank you, Eric!
