### ISSUE TITLE
Susy debug has extra gutter in last column (only in Chrome)

### ISSUE THREAD

**Issue by krzkrzkrz** [ericam/susy#494]
My Susy config looks like:

    $susy: (
      columns: 16,
      debug: (image: columns)
    );

Firefox renders with:

![screen shot 2015-06-26 at 11 32 03 pm](https://cloud.githubusercontent.com/assets/390072/8380992/9ddcc6e2-1c5b-11e5-800c-56c01f1ce942.png)

Chrome renders with:

![screen shot 2015-06-26 at 11 32 12 pm](https://cloud.githubusercontent.com/assets/390072/8380995/a246339e-1c5b-11e5-8600-6715141a3155.png)

Notice, on the last column, in Chrome, there is an extra gutter.

**Comment by ericam** [comment]
This is a known browser bug that only affects the background image. See #473 and #440.
