### ISSUE TITLE
Susy aligning contents different in Chrome

### ISSUE THREAD

**Issue by krzkrzkrz** [ericam/susy#495]
I created a simple layout. All displays fine in Firefox, but not in Chrome. The differences get noticeable with the `aside` and `article` elements.

I am guessing, it has something to do with Chrome handling sub pixel rounding. If so, how do I go about this?

I attached screenshots from Firefox and Chrome below.

    // css
    .side-navigation     { @include span(2 of 16); }
    .content             { @include span(14 of 16 last);
      .top               { @include span(14 of 14 last); background-color: $prototype-amber; }
      .center            { @include span(14 of 14 last);
        aside            { @include span(7 of 14); background-color: $prototype-pink; }
        article          { @include span(7 of 14 last); background-color: $prototype-teal; }
      }

    }

    // html
    <body>
      <aside class="side-navigation">
        side navigation
      </aside>

      <main class="content">
        <section class="top">
          top
        </section>

        <section class="center">
          <aside>aside</aside>
          <article>article</article>
        </section>
      </main>
    </body>

Firefox:
![screen shot 2015-06-26 at 11 41 10 pm](https://cloud.githubusercontent.com/assets/390072/8381418/1f2e6f78-1c5e-11e5-84cf-fbc466898b0f.png)

Chrome:
![screen shot 2015-06-26 at 11 41 27 pm](https://cloud.githubusercontent.com/assets/390072/8381425/269fdd78-1c5e-11e5-8cc8-aee22520c633.png)

**Comment by ericam** [comment]
You don't need to do anything. It's working fine, but the background grid image is not reliable in all browsers. Turn that off and you'll see that both layouts are identical. Resize the browser and the grid image will shift. See #473 and #440.

**Comment by zellwk** [comment]
@krzkrzkrz This is due to how browsers render subpixels (pixels lesser than 1px). Chrome and Safari round them down while Firefox renders subpixels perfectly. That's why the grid looks slightly wrong on Chrome.
