### ISSUE TITLE
Is it possible to have a gutter on right side of the last column?

### ISSUE THREAD

**Issue by krzkrzkrz** [ericam/susy#496]
Is it possible for Susy to always expose a gutter on the right side of the last column?

The reason, being so it acts as a sort of padding. So the elements on the last column don't hang out on the "edge". If that makes sense.

**Comment by ericam** [comment]
Yes, assuming you need that padding on the left as well. Susy has several gutter settings that give you side padding on both edges: `split` (both margins), `inside` (padding on both sides), and `inside-static` (non-% padding on both sides).
