### ISSUE TITLE
Breakpoint variable $normal outputting odd value

### ISSUE THREAD

**Issue by courtbee** [ericam/susy#498]
Using Susyone, not sure if applicable to Susy Two.

I defined a breakpoint as `$normal : 960px 12 1024px;` but when I checked the output in the CSS file, it had written `min-width: 1999em`.

Changing the variable name fixed the issue. I checked docs to see if maybe `$normal` was reserved for something else but didn't find anything applicable.

**Comment by ericam** [comment]
I can't find a variable named `$normal` anywhere in the source code either. Maybe coming from the `beakpoint` plugin?

**Comment by courtbee** [comment]
Hey ericam, could I have a little clarification? 

I didn't install anything other than Susy. Is the `breakpoint` plugin you mention a part of compass or something else? 

Thanks!

**Comment by ericam** [comment]
Oh, sorry that wasn't relevant to your case. What version of Susy do you have installed?

**Comment by courtbee** [comment]
I'm using susy 1.0.5. It's what was packaged with the compass.app. I'm going to do a little investigating today with other frameworks available with the compass.app to see if I experience anything similar with the `$normal` variable. 

I may have jumped the gun a bit posting this here because now that I think about it a bit more, it might be related to the compass.app. I had to use an older version (1.26 of the app) because the later version had a permissions bug.

In any case, I'll update the issue or close it depending on what I find. Thanks for such a prompt response! :D

**Comment by ericam** [comment]
Ok, it could also be that there was a `$normal` variable in 1.0.5 that no longer exists in the current repo. Let me know if you need me to go back and look.

**Comment by courtbee** [comment]
I figured it out and it was totally my fault. Now I feel slightly embarrassed.
