### ISSUE TITLE
Documentation site's css not applied

### ISSUE THREAD

**Issue by emilime** [ericam/susy#499]
http://susydocs.oddbird.net/ appears unstyled (on Chrome dev) 
in console log I see:

Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "https://media.readthedocs.org/css/sphinx_rtd_theme.css".

Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "https://media.readthedocs.org/css/readthedocs-doc-embed.css".

**Comment by ericam** [comment]
This seems to be an issue in our [readthedocs](https://readthedocs.org) build. Looking into it.
