### ISSUE TITLE
Susy gutter-position after and calculating to 100% - gutter width

### ISSUE THREAD

**Issue by mjot** [ericam/susy#503]
Hi,

I would like to know if it is possible to configure susy for the following behaviour:

I would like to work with gutter-position: after but without using the last keyword for the last container in a row. Is it possible to change the gutter and col calculation from susy so that it calculates to 100% - gutter width?

If I have the following setup:

    $susy : (
      columns: 2, 
    );
  
    .wrap {
      @include container(600px);
      height: 50vh;
      div{
        @include span(1 of 2);
        &:last-of-type{
          @include span(1 of 2 last);
        }
      }
     }

And the following code:

    <div class="wrap">
      <div>Col 1</div>
      <div>Col 2</div>
    </div>

If I don't use the "last" parameter, susy calcs like this:
44.4444% + 11.1111% + 44.4444% + 11.1111% = 111,111%

If I'm removing the right margin for the last col with the "last" parameter susy calcs like this:
44.4444% + 11.1111% + 44.4444% = 99,9999%

I would like to change the behaviour so that I have a gutter at the start and the end of my grid.
So I would like to give the wrapper a padding with the width of the gutter. I know the split setting, but I need the full gutter width, not only the half.

So It would be great if susy could calculate the cols to 100% - gutter; Maybe this could be combined with the "nest" parameter used at the wrapper?

Here is an example to visualize the idea:

![unbenannt-1_bei_100___ebene_1__rgb_8___](https://cloud.githubusercontent.com/assets/1445991/8873962/43e7ae60-320c-11e5-8d15-f2029965347f.png)

I hope this is possible, thanks so much Eric!

**Comment by ericam** [comment]
There is no built-in way to do this, though the core math engine would support most of it (which means you could build your own tools around it). You can get close by using the `split` gutter-position, with a little padding added to your container.

The main problem is that your container `padding-left` percentage is relative to a different context than your columns/gutters — so giving them the same `%` value won't work. The container padding is relative to the full container width, but the columns and gutters are being calculated relative to the container *content* (width minus padding). It would take a bit of extra math to calculate that difference in context.
