### ISSUE TITLE
Centering of a row

### ISSUE THREAD

**Issue by C4Grey** [ericam/susy#504]
Is it possible to center a row in a container? I've made some search and found only [this SO question](http://stackoverflow.com/questions/25976434/susy-center-elements-in-last-row-of-gallery). Since there are no relevant functions or mixins to deal with centering of a row, maybe it can be done with some additional CSS/SCSS code(without breaking of the existing algorithms of positioning, what is a most important thing)? [Here is an example](http://sassmeister.com/gist/c7e1f72854e26cd1e857) that may help to understand a desired behaviour.

**Comment by ericam** [comment]
For the best automated solution, use flexbox. [Here's a demo](http://sassmeister.com/gist/147e050803b5ab8bf12d) based on yours. 

Any other (float-based) approach will require complex `nth-child` calculations, or JS interference, or some other crazy hackery.

**Comment by C4Grey** [comment]
Looks fine, thank you...somehow a top margin of divs is missing in the Firefox browser, but it can be figured out.
