### ISSUE TITLE
Susy problems in safari/chrome on Ipad 5.1.1

### ISSUE THREAD

**Issue by mooror** [ericam/susy#506]
Hey there Eric, I was recently testing a clients website on multiple browsers and devices when I came across a total breakdown of the susy grid on ipad 5.1.1. Here is what I mean by totally breaks down.

Desktop Browser (Firefox 40.0.2)
![urbancurbn on desktop](https://cloud.githubusercontent.com/assets/6110819/9294536/64388032-440d-11e5-9fa6-ff7642306ce4.png)

Ipad 5.1.1 Browser (chrome and looks the same on safari)
![urbancurbn on tablet 5 1 1](https://cloud.githubusercontent.com/assets/6110819/9294537/6f1254ce-440d-11e5-996a-2f90dae15ae4.PNG)

I think that this may be due to the sub pixel errors in old webkit browsers. I didn't know if this was a problem that susy could fix as it seems to be built on technology that is lacking in older browsers. I wanted to check my theory so I checked out your oddbird website on the same device (and browser). To my surprise your site came up just fine. Is this because you are using the isolate grid technique? Or is it some hack you needed to use? please respond as soon as possible.

Thanks in advance,
Mooror

**Comment by zellwk** [comment]
Are you on IE8? If so, check this out: http://www.zell-weekeat.com/support-for-older-browsers/




Stay Awesome!  Zell

**Comment by ericam** [comment]
I don't have access to Safari 5 for testing, but what you are seeing doesn't look like a sub-pixel rounding error — or anything I've seen before (and Susy has been around since the IE6 days). Susy is based entirely on floats, so it's not some new technology — and iOS Safari 5 should even support Media Queries (as long as they aren't nested). That was my first guess, because it looks like widths are not being respected at all. I would have to see your code, or possibly dig into a debugger, to understand what's going on there.

**Comment by mooror** [comment]
Thank you sir for your response. And after digging into it for the past two days I would have to agree with your diagnoses. The strange thing is that I have no nested media queries. So I looked into the cause of media queries being ignored in safari and found that safari seems to handle css errors a little bit differently then other browsers and therefor if your missing a bracket somewhere the code will barf. When I found this i decided to validate my css to find out if I had any of theses missing brackets. Turns out I do. So now I have to go through my entire scss markup looking for this darn thing. So though the problem is not solved for me I think we can safely close this issue, as susy doesn't seem to be the culprit. 

P.s. Do you have any ideas on how I might diagnose where my missing brace might be (in my scss markup)?

**Comment by ericam** [comment]
If you have a missing brace in Scss, the parser should catch it and complain. Any chance you are including some CSS files directly?

**Comment by mooror** [comment]
Yes I am including quite a few plain css files as well as using zurb foundation 5's scss. But the error was found inside one of my css files(generated from scss). But now that you mention it I havent tried removing foundation from my scss... Thank you for the idea. I will try it

**Comment by mooror** [comment]
No Dice. I removed the entire foundation 5 library and it still displays wrong. This is getting frustrating (actually it already was :D)

**Comment by mooror** [comment]
Well I figured it out Eric. Turns out that my media queries where defined as rem units instead of pixels. I guess the most browsers are fine with that while ios 5.1.1 safari and chrome..not so much. So I thank you for all your help. 

God Bless

**Comment by ericam** [comment]
Glad you tracked it down! Happy coding!
