### ISSUE TITLE
Add scss-linter and code style guide

### ISSUE THREAD

**Issue by ericam** [ericam/susy#515]

**Comment by HugoGiraudel** [comment]
I you feel okay with Sass Guidelines, I suggest we follow them as they are very extensive. If there are things from there you don't like, we can totally extend them as we did for SassDoc (with JS guidelines): https://github.com/SassDoc/sassdoc/blob/master/GUIDELINES.md. I'm not precious about them, we can adapt them to suit our needs.

For SCSS-Lint, there is a Sass Guidelines compliant configuration file: http://sass-guidelin.es/#scss-lint.

**Comment by Snugug** [comment]
If you're looking for a full Node stack, a Node only Sass Linter now exists too!
https://github.com/sasstools/sass-lint/

**Comment by HugoGiraudel** [comment]
Is it ready for usage or is it still in beta?

**Comment by ericam** [comment]
@HugoGiraudel let's start with Sass Guidelines and I'll let you know if I hate it. :)

We won't be node-only in either case (we still want to test and release a gem for Ruby Sass) — but I'm not opposed to using the node linter if it does what we need. @HugoGiraudel are you willing to make that call and set up linting for us?

**Comment by HugoGiraudel** [comment]
Done in https://github.com/ericam/susy/commit/e15e60f2354c47f13218f375174648128cdc7845.

**Comment by ericam** [comment]
\o/
