### ISSUE TITLE
Provide unprefixed public API

### ISSUE THREAD

**Issue by HugoGiraudel** [ericam/susy#518]

**Comment by HugoGiraudel** [comment]
How would you like to tackle this @ericam? I would recommend we do not unprefix variables as we have few of them, they are not meant to be used but only read from and it can be risky given how common their name are.

For functions, we can either provide an unprefixed version after the declaration but that might get messy quite quick, or we could provide a file which unprefix everything. This file would not be imported by default, and authors can import it to unprefix the API.

**Comment by ericam** [comment]
closed by 3d13d5d
