### ISSUE TITLE
Push mixin

### ISSUE THREAD

**Issue by dsushmasagar** [ericam/susy#528]
When I applied push mixin on desktop resolution it works fine. http://sassmeister.com/gist/00ab2ef69b57e3b803cf 
When try to apply the push mixin in my mobile media query that was changing my desktop styles.
http://sassmeister.com/gist/0f686ecceadeec061e53.

Am I doing it in right way?

**Comment by ericam** [comment]
What result are you hoping for? The `push` mixin just adds left margins to an element.

**Comment by dsushmasagar** [comment]
How to avoid overwriting push margins from mobile to desktop?

**Comment by ericam** [comment]
There are two ways to handle different styles at different media-queries (whether `push` or anything else):

1. Use restricted media queries, with both a `min` and `max` width, so they only apply where desired.
2. Override your earlier settings with more specific settings later (in this case, set `margin-left: 0;` in the other media-query.

I prefer option 1 in most cases.

If you really just want stacked items in your mobile view, I wouldn't use Susy at all for that. Items stack be default. Set your margins to `auto` and the elements will center themselves.

**Comment by dsushmasagar** [comment]
Thankyou.

**Comment by HugoGiraudel** [comment]
Looks solved, I close. :)
