### ISSUE TITLE
Static gutter inside-static

### ISSUE THREAD

**Issue by Grafikart** [ericam/susy#529]
Is it possible to have a static gutter (20px) without having to define neither a container width or column width ? Something like 

```scss
$layout: layout(12 inside-static 10px);
```

at the moment we are forced to do 

```scss
$susy: (
  container: 960px,
  columns: 4,
  gutters: 20px/100px,
  gutter-position: inside-static,
  column-width: 100px,
  container-position: -10px
);
```

The problem of this setting is the fact it automatically gives a max-width to all containers :(

By the way I have a global border-box ^^

**Comment by ericam** [comment]
`$layout: layout(100% 4 (100px 20px) inside-static);` is the shorthand, where `100%` is keeps your container fluid. That's the same as:

```
$layout: (
  container: 100%,
  columns: 4,
  gutters: 20px/100px,
  gutter-position: inside-static,
  column-width: 100px,
);
```

You do need the `column-width` (I understand that's a bit confusing in this case) — but you don't need it to change the `container` at all.

**Comment by HugoGiraudel** [comment]
@ericam Can we close?
