### ISSUE TITLE
PM: Message: may only compare numbers

### ISSUE THREAD

**Issue by munjiza** [ericam/susy#531]
When I try to compile any .scss file, this is what I get:

     10/1/2015 6:11:18 PM: SCSS: Compiling file.scss
     10/1/2015 6:11:20 PM: Looking for resource @ http://localhost.:27610/
     10/1/2015 6:11:21 PM: Message: may only compare numbers

Also:
      Compilation Error occurred (see error list to navigate to the error location):
      Error found at line 104, column 23:
      Code: undefined Message: may only compare numbers

When I open this files on my amother computer, everyhing is ok. I tried to reinstall WebEssentials (thought it was making troubles) but it didn't help me at all.
Anyone familiar with this?

**Comment by munjiza** [comment]
EDIT: When I comment this part of code (around line 104) then I get another error.. but I guess someone can figure out from this what might be the problem.

    // Deep Has-Key
    // ------------
    // - Return true if a deep key exists
    @function _susy-deep-has-key(
      $map,
      $keys...
    ) {
      $_return: null;
      $_stop: false;
     
      @each $key in $keys {
        @if not($_stop) {
          $_return: map-has-key($map, $key);
        }
     
        @if $_return {
          $map: map-get($map, $key);
        } @else {
          $_stop: true;
        }
      }

  @return $_return;
 }

**Comment by ericam** [comment]
That error doesn't make sense with that line of code.

We've seen this error before — because of an old LibSass bug (I don't know anything about WebEssentials), or because user settings are wrong. Can you paste the settings for your project?

**Comment by munjiza** [comment]
Hope this is what you are looking for (_settings.scss from susy folder):

     // Settings
     // ========
     
     // Version
     // -------
     $su-version: 1.1;
     
     
     // Default Settings
     // ----------------
     // PRIVATE: The basic settings
     $susy-defaults: (
       columns: 4,
       gutters: 1/4,
     );
     
     
     // User Settings
     // -------------
     // - Define the $susy variable with a map of your own settings.
     // - Set EITHER $column-width OR $container
     // - Use $column-width for static layouts
     $susy: () !default;
     
     
     // Susy Defaults
     // -------------
     // PRIVATE: Add defaults to Susy
     @mixin susy-defaults(
       $defaults
     ) {
       $susy-defaults: map-merge($susy-defaults, $defaults) !global;
     }
     
     
     // Susy Set
     // --------
     // Change one setting
     // - $key   : setting name
     // - $value : setting value
     @mixin susy-set(
       $key-value...
     ) {
       $susy: _susy-deep-set($susy, $key-value...) !global;
     }
     
     
     // Susy Get
     // --------
     // Return one setting from a grid
     // - $key     : <keyword>
     // - $layout  : <settings>
     @function susy-get(
       $key,
       $layout: map-merge($susy-defaults, $susy)
     ) {
       $layout: parse-grid($layout);
       $_options: $layout $susy $susy-defaults;
       $_break: false;
       $_return: null;
     
       @each $opt in $_options {
         @if type-of($opt) == map and not($_break) {
           $_keyset: _susy-deep-has-key($opt, $key...);
           @if $_keyset {
             $_return: _susy-deep-get($opt, $key...);
             $_break: true;
           }
         }
       }
     
       @return $_return;
     }

**Comment by ericam** [comment]
Nope, all the code you are pasting is the Susy code I wrote. I need to see the code *you* wrote. How are you using Susy?

But I have a guess. Looks like you are using an older version of Susy, and probably an older version of Libsass that couldn't handle fractions (like that `gutters: 1/4` line). That would cause the error you are seeing. If you can upgrade either Susy, or Libsass (or both) that should fix it. Otherwise simply add your own `gutters` setting without using fractions.

**Comment by munjiza** [comment]
@ericam  sorry. It was me. I did not set TRUE for 'Use Ruby Runtime' in WebEssentials settings. When I changed it from 'false' to 'true', everything is working as expected.

Leaving screenshot here for everyone else who might do same mistake as I did.
Thank you. 
![WebEssentials settings](http://i.imgur.com/8kLcwdB.png)

**Comment by HugoGiraudel** [comment]
So can we close this?

**Comment by munjiza** [comment]
Yes @HugoGiraudel we can close this. Ty
