### ISSUE TITLE
Debug image is rendered incorrectly when setting container-position to a length

### ISSUE THREAD

**Issue by ambvdijk** [ericam/susy#532]
If have a fluid layout with the following overrides to the default settings:

```scss
$susy: (
  columns: 24,
  gutters: .25,
  container-position: 1em,

  debug:(
      image: show,
      toggle: top left,
      output: background
    ),
);
```

In order to give the entire container some margins from its viewport I set the container-position to 1em.
It looks like the debug image completely ignores these margins when rendering.

Setting the container-position to an absolute unit renders a better debug background, but far from what it should be.

**Comment by ericam** [comment]
I can't recreate this. What you might be noticing is that the background image does not always align perfectly to the container. That's a [known browser-bug (see the warning)](http://susydocs.oddbird.net/en/latest/toolkit/#show-grid) related to sub-pixel rounding (so affected by your container width).

**Comment by ambvdijk** [comment]
I'll try to create a codepen to see if I can reproduce this behavior. 
The sub-pixel rounding should be off by a little right? The behavior I saw was off by a lot ;-)

**Comment by ambvdijk** [comment]
Here is a sample codepen:
http://codepen.io/anon/pen/NGpVmR

**Comment by ambvdijk** [comment]
I only see this behavior in Chrome by the way!
I justed tested IE 11, and there it looks perfectly aligned!

**Comment by ericam** [comment]
Unfortunately it can be off up to 1px *per column*, so with your large column count, that's a big difference. The way to check if it's a sub-pixel rounding error is to re-size the browser. It should line up perfectly at some widths, and not others.

**Comment by ambvdijk** [comment]
Ah ok, That would explain it. Thank you for your response!

**Comment by HugoGiraudel** [comment]
Is it solved? Can we close?
